version: '3.8'

services:
  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=123123123JJ23KJ123
      - ALLOWED_HOSTS=localhost,127.0.0.1